services:
  postgres:
    image: postgres
    container_name: parcels_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-rest-client

  parcelloader:
    build:
      context: ./parcelloader
    container_name: parcelloader
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - spring-rest-client
    depends_on:
      - postgres

  consoleclient:
    build:
      context: ./consoleclient
    container_name: consoleclient
    ports:
      - "8081:8081"
    environment:
      PARCEL_LOADER_URL: "http://parcelloader:8080"
    networks:
      - spring-rest-client
    depends_on:
      - parcelloader

  telegramclient:
    build:
      context: ./telegramclient
    container_name: telegramclient
    environment:
      PARCEL_LOADER_URL: "http://parcelloader:8080"
    env_file:
      - telegramclient/credentials.env
    ports:
      - "8082:8082"
    networks:
      - spring-rest-client
    depends_on:
      - parcelloader

networks:
  spring-rest-client:
    driver: bridge