spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

topics:
  billing:
    orders: parcels.orders.0

task:
  executor:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 500
    thread-name-prefix: async-
  scheduler:
    pool-size: 5
    thread-name-prefix: Scheduler-
  send-unprocessed-orders:
    rate-ms: 1000

parcels:
  delimiter: