spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    function:
      definition: "orders"
    stream:
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        orders-in-0:
          destination: parcels.orders.0
          group: billing_logistic_v0
          contentType: application/json

billing:
  pricing:
    load: 80
    unload: 50